name: Server Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd server
          npm ci

      - name: Run tests
        run: |
          cd server
          npm test
        env:
          YOUR_ENV_VAR: ${{ secrets.API_NAME }}
          ANOTHER_ENV_VAR: ${{ secrets.PUBLISHER_NAME }}
